### PR TITLE
Update gfm.cson for Kotlin highlighting

### PR DESCRIPTION
**Pull request by radixdev**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Adds [Kotlin](http://kotlinlang.org/) syntax highlighting for code blocks.

### Alternate Designs

n/a

### Benefits

The Kotlin language can now have syntax highlighting when editing markdown code blocks. This increases readability when editing markdown.

Github supports Kotlin highlighting, see the below.

```kotlin
    // Firebase tokens cannot be obtained on the main thread.
    Thread(Runnable {
      try {
        val token = FirebaseInstanceId.getInstance().getToken("<YOUR_SENDER_ID>", "FCM")
        Appboy.getInstance(applicationContext).registerAppboyPushMessages(token)
      } catch (e: Exception) {
        Log.e(TAG, "Exception while registering Firebase token with Braze.", e)
      }
    }).start()
```

### Possible Drawbacks

I do not foresee any drawbacks to Kotlin language highlighting.

### Applicable Issues

https://github.com/atom/language-gfm/issues/166

### CODE REVIEW

**Comment by radixdev** [comment]
@50Wliu

**Comment by radixdev** [comment]
@jasonrudolph ??

**Comment by rsese** [comment]
Sorry about that @radixdev - just wanted to acknowledge that someone from the team will take a look as soon as they can.

**Comment by 50Wliu** [comment]
Thank you!

**Pull request merged**
