### PR TITLE
Add support for embedding Python Console feedback

### PR DESCRIPTION
**Pull request by Alhadis**
This is an attempt to fix github/linguist#1939.

Please advise if you need a spec to be included.

### CODE REVIEW

**Comment by Alhadis** [comment]
@50Wliu Any chance of getting this merged within the following weeks?

Just interested in knowing if it'll have a chance to make the next release of [Linguist](https://github.com/github/linguist), which ships every few weeks. =)

**Comment by Alhadis** [comment]
Hrm, I guess not.

FYI, the grammar *is* [bundled with Atom](https://github.com/atom/language-python/blob/master/grammars/python-console.cson).

**Comment by 50Wliu** [comment]
Thanks for the clarification.

**Comment by Alhadis** [comment]
Sorry it took me almost a whole week before I picked up on that, heh...

**Pull request merged**
