### PR TITLE
added inline syntax highlighting for liquid

### PR DESCRIPTION
**Pull request by puranjayjain**
adds shopif snippets to gfm.
trying to solve #145

### CODE REVIEW

**Comment by fusion809** [comment]
Ah. Snippets aren't the issue, #145 is about syntax highlighting for Liquid not snippets.

**Comment by puranjayjain** [comment]
@fusion809 totally got confused removing that and adding the relevant files

**Comment by fusion809** [comment]
Ah, I don't think ya quite understand what #145 is all about still. I don't want this package to syntax highlighting `.liquid` files, I want this package to syntax highlight Liquid code that is embedded in Markdown files.

**Comment by puranjayjain** [comment]
@fusion809 ah now I get your exact problem.

**Comment by puranjayjain** [comment]
@fusion809 yes I think that was what you wanted.
What I thinkg is that problem could be solved by adding including gfm and markdown language in the liquid language package that way the liquid snippets will present and all the relevant liquid and markdown sytax both will be higlighted. What are your thoughts about it @burodepeper

**Comment by fusion809** [comment]
@puranjayjain You are missing a `}` at the end of the grammars/gfm.cson file. After making this fix locally on my machine I found the package is not providing the inline liquid syntax-highlighting I expected.

**Comment by fusion809** [comment]
@puranjayjain Any ideas of how to solve this problem and make the package provide syntax-highlighting for my Liquid tags?

**Comment by burodepeper** [comment]
I'll look at this later today. Should be an easy fix.

**Comment by burodepeper** [comment]
Quick update: I noticed that some things have to be fixed in `language-liquid` too to address @fusion809's original issue. No big issues though.

@puranjayjain I think it's easiest if you close this PR, and then I'll create a new one.

**Comment by puranjayjain** [comment]
ok

**Pull request closed without merging**
