### PR TITLE
feat: add 'properties' support

### PR DESCRIPTION
**Pull request by ldez**
add support for 'properties' source.

I use `java-properties` but it's possible to use `git-config` for a better support.
What do you think ?

GitHub use `git-config` as support for the `properties` marker:

``` properties
[user]
    name = John Doe
    email = example@examplecom
```

### CODE REVIEW

**Comment by ldez** [comment]
Any news?

**Comment by daviwil** [comment]
Hi @ldez!  Thanks a lot for the PR.  If you think using `git-config` will lead to a better result, please give it a try.  Could you also add a test to ensure that the language gets parsed correctly?

**Comment by daviwil** [comment]
Thanks a lot for making those changes!  The tests are green, think this is ready to go?

**Comment by ldez** [comment]
Do you want me to add more tests?

**Comment by daviwil** [comment]
Only if there's something else you feel is worth testing.  Looks like you've added similar tests as the ones for other embedded languages, so I think it should be sufficient.

**Comment by ldez** [comment]
Ok seems good to me.

FYI:
- `java-properties`
java-properties

- `git-config`
git-config

**Comment by daviwil** [comment]
Thanks a lot for the comparison!  Definitely better to go with `git-config`, it seems.  I'll merge this now and ship an update to be included with 1.29.0-beta0 🎉

**Pull request merged**
