### PR TITLE
allow for more generic expressions in R (.Rmd)

### PR DESCRIPTION
**Pull request by pimentel**
Currently only code blocks that start with `r ` are supported for Rmd (Rmarkdown). In practice, you commonly have a block that start like this: 

`{r}`

or

`{r, cache=TRUE}`

the possibility of no or many arguments.

This pull request allows these types of expressions. Unfortunately, it doesn't intelligently insert the language type when `engine=` is set to anything other than `R` (you could set it to things such as `bash`, `python`, etc.). In this case, it would simply set the language to R.

### CODE REVIEW

**Comment by pimentel** [comment]
Happy new year!

Ping for review. This is pretty important for R users. Thanks!

**Comment by jeffjjohnston** [comment]
I would also be very interested in having this feature added. Thanks!

**Comment by kevinsawicki** [comment]
@pimentel would you mind adding a spec for this just to assure the regex is performing as expected?

**Comment by pimentel** [comment]
@kevinsawicki I can try to do so today. thanks!

**Comment by pimentel** [comment]
@kevinsawicki, sorry I missed the specs the first time around. Anyway, I caught a small bug and added some specs.

Let me know if there is anything else I can do to help. Thanks!

**Comment by kevinsawicki** [comment]
Awesome, thanks for this, apologies for the delay in merging :ship:

**Comment by cnjr2** [comment]
thanks a lot for this feature; fully switched to atom now!

**Comment by pimentel** [comment]
@cnjr2 that's great! have you seen [r-exec](https://atom.io/packages/r-exec)? I am actively working on it hope to make it better in the future.

@kevinsawicki thanks a bunch for merging this! any idea why it's not updating for me in the Atom Package Manager? Also, (if you know) is it possible to see the version that is published on atom.io/packages somewhere? I can't seem to find it. Thanks a bunch!

**Comment by 50Wliu** [comment]
> any idea why it's not updating for me in the Atom Package Manager (it currently shows v0.82.0)?

This is a bundled package, so it only gets updated when Atom is updated.  Right now it looks like it'll be included in 1.6.0.

**Pull request merged**
